title: Dag- og aftenskolen i Rønde
email: info@dag-aftenskolen.dk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dag-aftenskolen.dk" # the base hostname & protocol for your site, e.g. http://example.com
exclude: [build.sh, deploy.sh, serve.sh, README.md, Gemfile, Gemfile.lock]

# Build settings
encoding: UTF-8
